# Generated by Django 3.1.7 on 2021-03-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210316_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
